apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - image: bmuschko/web-app:1.0.1
    name: secret-pod
    volumeMounts:
      - name: secret-volume
        readOnly: true
        mountPath: /etc/secret
  volumes:
    - name: secret-volume
      secret:
        secretName: basic-auth
          
